#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

build_folder=build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cp ../hoofdstukken/Voorwoord/*.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md
cp ../hoofdstukken/3D1/*.* $build_folder      ; mv $build_folder/README.md $build_folder/README_01.md
cp ../hoofdstukken/3D2/*.* $build_folder      ; mv $build_folder/README.md $build_folder/README_02.md
cp ../hoofdstukken/3D3/*.* $build_folder      ; mv $build_folder/README.md $build_folder/README_03.md
cp ../hoofdstukken/3D4/*.* $build_folder      ; mv $build_folder/README.md $build_folder/README_04.md

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_03.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_04.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md

pandoc README.md -o Boek_6.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in
mv Boek_6.pdf ../../boeken/Boek_6_zonder_voorpagina.pdf

cd ../../boeken
pdfunite Boek_voorpagina_6.pdf Boek_6_zonder_voorpagina.pdf Boek_6.pdf

# Make booklet
bookletimposer -a Boek_6.pdf -o Boekje_6.pdf

rm Boek_6_zonder_voorpagina.pdf
