#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

build_folder=build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cp ../hoofdstukken/Voorwoord/*.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md
cp ../hoofdstukken/Minim0/*.* $build_folder   ; mv $build_folder/README.md $build_folder/README_01.md
cp ../hoofdstukken/Minim1/*.* $build_folder   ; mv $build_folder/README.md $build_folder/README_02.md

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md

pandoc README.md -o Boek_Minim.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in
mv Boek_Minim.pdf ../../boeken/Boek_Minim_zonder_voorpagina.pdf

cd ../../boeken
pdfunite Boek_voorpagina_Minim.pdf Boek_Minim_zonder_voorpagina.pdf Boek_Minim.pdf

# Make booklet
bookletimposer -a Boek_Minim.pdf -o Boekje_Minim.pdf

rm Boek_Minim_zonder_voorpagina.pdf
